project:
  type: website

website:
  title: "AI vs. Non-AI Careers"
  navbar:
    left:
      - about.qmd
      - text: Introduction
        file: research_introduction.qmd
      - href: data_analysis.qmd
        text: Exploratory Data Analysis
      - href: skill_gap_analysis.qmd
        text: Skill Gap Analysis
      - href: rf_regression.qmd
        text: Random Forest Regression
      - href: KMeans_clustering_methods.qmd
        text: K-Means Clustering

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



