project:
  type: website
  render: 
        - index.qmd
        - about.qmd
        - research_introduction.qmd
        - data_analysis.qmd
        - skill_gap_analysis.qmd
        - KMeans_clustering_methods.qmd
        - lr_regression.qmd
website:
  title: "AI vs. Non-AI Careers"
  navbar:
     background: "#24819c"   # navbar bg color
     foreground: "white"     # navbar text/icon color
     left:
      - about.qmd
      - text: Introduction
        file: research_introduction.qmd
      - href: data_analysis.qmd
        text: Exploratory Data Analysis
      - href: skill_gap_analysis.qmd
        text: Skill Gap Analysis
      - href: KMeans_clustering_methods.qmd
        text: K-Means Clustering
      - href: rf_regression.qmd
        text: Random Forest Regression
      

bibliography: references.bib
csl: csl/econometrica.csl

format:
  html:
    toc: true
    number-sections: true
    title-block-banner: true
  docx: default

title: AI vs. Non-AI Careers
subtitle: "Final Report"
author:
  - name: Kelly, Sabrina, Makenzie
    affiliations:
      - id: bu
        name: Boston University
        city: Boston
        state: MA
date: '2025-10-15'
date-modified: today
date-format: long