project:
  type: website

website:
  title: "AI Jobs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Introduction
        file: research_introduction.qmd
      - href: data_analysis.qmd
        text: Data Cleaning and Exploratory Data Analysis
      - href: skill_gap_analysis.qmd
        text: Skill Gap Analysis
      - href: ml_methods.qmd
        text: ML Methods
      - href: clustering_methods.qmd
        text: KMeans Clustering

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



