project:
  type: website

website:
  title: "AI Jobs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Introduction
        file: research_introduction.qmd
      - href: data_analysis.qmd
        text: Data Analysis


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



